export const antdTheme = {
  token: {
    colorPrimary: "#2fb79c",
    borderRadius: 10,
    fontSize: 13,
    fontFamily: '"Avenir Next", "Source Sans 3", "Segoe UI", sans-serif',
    colorText: "#0f1b2d",
    colorBgLayout: "#f0fbf7",
  },
  components: {
    Layout: {
      siderBg: "#ffffff",
      headerBg: "#ffffff",
      bodyBg: "#f0fbf7",
    },
    Menu: {
      itemHeight: 42,
      itemBorderRadius: 10,
      itemSelectedBg: "#3BC2A7",
      itemSelectedColor: "#ffffff",
      itemHoverBg: "rgba(59,194,167,0.14)",
      groupTitleColor: "#6b7a85",
    },
    Table: {
      headerBg: "#f3f7fa",
      headerColor: "#4b5563",
      rowHoverBg: "rgba(15,27,45,0.03)",
      borderColor: "rgba(15,27,45,0.1)",
      cellPaddingBlock: 10,
      cellPaddingInline: 12,
      fontSize: 13,
    },
    Tooltip: {
      colorBgSpotlight: "#0f1b2d",
    },
  },
};

export const antdThemeCleanV2 = {
  token: {
    colorPrimary: "#1A2E4B",
    colorInfo: "#1A2E4B",
    colorLink: "#1A2E4B",
    colorSuccess: "#2E7D32",
    colorWarning: "#C5A059",
    colorError: "#D32F2F",
    borderRadius: 10,
    borderRadiusLG: 12,
    fontSize: 13,
    fontFamily: '"Avenir Next", "Source Sans 3", "Segoe UI", sans-serif',
    colorText: "#1A2E4B",
    colorTextSecondary: "#6B7280",
    colorTextTertiary: "#8B96A5",
    colorBgLayout: "#F2F4F7",
    colorBgContainer: "#FFFFFF",
    colorBorder: "#D1D5DB",
    colorBorderSecondary: "#E5E7EB",
    controlHeight: 36,
    controlHeightSM: 30,
  },
  components: {
    Layout: {
      siderBg: "#FFFFFF",
      headerBg: "#F8FAFC",
      bodyBg: "#F2F4F7",
    },
    Menu: {
      itemHeight: 40,
      itemBorderRadius: 10,
      itemSelectedBg: "#1A2E4B",
      itemSelectedColor: "#FFFFFF",
      itemHoverBg: "rgba(26,46,75,0.08)",
      itemHoverColor: "#1A2E4B",
      itemColor: "#6B7280",
      groupTitleColor: "#6B7280",
    },
    Card: {
      borderRadiusLG: 12,
      colorBorderSecondary: "#D1D5DB",
      bodyPadding: 14,
      headerFontSize: 18,
      headerHeight: 54,
    },
    Button: {
      borderRadius: 10,
      controlHeight: 36,
      controlHeightSM: 30,
      defaultBorderColor: "#D1D5DB",
      defaultColor: "#1A2E4B",
      primaryColor: "#FFFFFF",
      colorPrimary: "#1A2E4B",
      colorPrimaryHover: "#223B5F",
      colorPrimaryActive: "#142338",
    },
    Input: {
      controlHeight: 36,
      activeBorderColor: "#1A2E4B",
      hoverBorderColor: "#1A2E4B",
    },
    InputNumber: {
      controlHeight: 36,
    },
    Select: {
      controlHeight: 36,
      optionSelectedBg: "rgba(26,46,75,0.08)",
    },
    Table: {
      headerBg: "#F8FAFC",
      headerColor: "#6B7280",
      rowHoverBg: "rgba(26,46,75,0.03)",
      borderColor: "#D1D5DB",
      cellPaddingBlock: 9,
      cellPaddingInline: 12,
      fontSize: 13,
      headerBorderRadius: 0,
    },
    Tag: {
      borderRadiusSM: 999,
      defaultBg: "#F8FAFC",
      defaultColor: "#1A2E4B",
    },
    Tooltip: {
      colorBgSpotlight: "#1A2E4B",
    },
  },
};
